incomplete assessment due to technical issues
learn-academy-2023-alpha/week-4-assessment-Melaza6 pull request #1
Opened 2023-03-13 16:16 UTC by Melaza6

# Submitting Week 4 Assessment

### ✅ Completed Files

Mark the following as confirmation that the files in this repository are complete.

- [ ] JavaScript Coding Challenges
- [ ] Ruby Coding Challenges
- [ ] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:
not completed will continue work and have it finished by tomorrow.

2023-03-15 17:50 UTC, Genemichael25 requested changes
Leo, I am requesting changes due to this being incomplete. Please let me know when you have submitted the complete assessment so I can review. Thanks

2023-03-17 22:22 UTC, elysemontano requested changes
Requested Changes:
- It looks like you are missing the looking ahead section in interview questions.  Please make sure to add those in and message me when you have made those changes. 

Other feedback, I really want to encourage you to reach out prior to turning in your assessment when you run into jest blockers that don't allow you to run your tests.  I left some feedback throughout your assessment for you to take a look at as well.  Otherwise, your code looks great and is displaying an advanced beginner skill assessment.

2023-03-17 22:22 UTC, elysemontano commented on code-challenges.test.js
> +// info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
I appreciate you providing this error, I think this might be telling you that you don't have the dependencies to run yarn jest just yet.  To do this you would run `yarn` to bring in all of the node_modules, and package.json.  I want to encourage you to reach out prior to turning in your assessment with these types of errors so you are able to run your tests and see what is happening.

2023-03-17 22:22 UTC, elysemontano commented on code-challenges.test.js
> + return array1.concat(array2.filter((value) => array1.indexOf(value) < 0))
Nice work in this section!  I appreciate that you still used console logs to check your outputs.

2023-03-17 22:22 UTC, elysemontano commented on interview-questions.md
> +Researched answer: Calling the hash followed by a key name within brackets grabs the value associated with that key.
Nice work in this section!  There are a few questions that were a little thinner, make sure to continue to extend your answers when possible.

2023-03-17 22:22 UTC, elysemontano commented on ruby-challenges.rb
> +def palindrome(string)
Nice work on the Ruby section!!  👏

2023-03-17 22:52 UTC, elysemontano approved these changes
Thank you for making those changes.  Approved!

2023-03-30 15:42 UTC, merged